name: Cypress Tests
on:
  push:
  pull_request:
    branches: [main, master]
jobs:
  cypress-run:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment: TEST
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v7
        with:
          # Records to Cypress Cloud
          record: true
          parallel: true # Runs test in parallel using settings above
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Cypress verify
        run: npx cypress verify
        env:
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}
          URL: ${{ vars.URL }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      - name: Run Cypress tests
        run: npm run cy:run
      - name: Upload Cypress artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
          retention-days: 10
